trigger:
  branches:
    include:
    - refs/heads/main
    - refs/heads/release/*

pool:
  vmImage: ubuntu-latest

parameters:
  - name: deployNonProd
    displayName: Deploy to NonProd
    type: boolean
    default: false

resources:
- repo: self

variables:
# Group variables
- group: CodeBuildDeploy-Global

- template: variables-infrastructure.yml

- template: variables-build.yml
- template: variables-env.yml
  parameters:
    isManual: ${{ variables['build.type.manual'] }}
    isRelease: ${{ variables['build.type.release'] }}
    deployNonProd: ${{ parameters.deployNonProd }}

# Versioning
- template: variables-versioning.yml
  parameters:
    buildTypeRelease: ${{ variables['build.type.release'] }}
    majorVersion: 1
    minorVersion: 0

name: $[variables['Build.Number']]

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Init_Vars
    displayName: Init Vars
    steps:
    - checkout: self
      displayName: 'Checkout Repo'

    - bash: |
        echo "build.type.release = $(build.type.release)"
        echo "SourceVersion = $(Build.SourceVersion)"
        echo "SourceVersion.Short = $(Build.SourceVersion.Short)"
        echo "Build Number = $(Build.Number)"
        echo "Version Assembly = $(Version.Assembly)"
        echo "Version File = $(Version.File)"
        echo "Version Informational = $(Version.Informational)"
        echo "Version Major = $(Version.Major)"
        echo "Version Minor = $(Version.Minor)"
        echo "Version Patch = $(Version.Patch)"
      displayName: Output Version

  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - job: Tag_Version
      displayName: Tag Version
      dependsOn:
        - Init_Vars
      steps:
      - checkout: self
        displayName: 'Checkout Repo'
        persistCredentials: true

      - script: |
          git tag $(Build.Number)
          git push origin $(Build.Number)
        workingDirectory: $(Build.SourcesDirectory)
        displayName: Tag Version in Git

- stage: Provision_NonProdEnterprise_Subscription
  displayName: Provision NonProd Enterprise Subscription
  dependsOn:
    - Build
  jobs:
  - job: Init_NonProdEnterprise_TFState
    displayName: Init NonProdEnterprise TFState
    steps:
    - template: create-tfstate-storage.yml
      parameters:
        location: 'uksouth'
        service_connection: $(Azure.Subscription.NonProdEnterprise)
        resource_group_name: $(Tf.State.NonProdEnterprise.RG)
        storage_account_name: $(Tf.State.NonProdEnterprise.SA)
        container_blob_name: $(Tf.State.NonProdEnterprise.Blob)

  - deployment: Provision_NonProdEnterprise_Platform
    displayName: Provision NonProdEnterprise Platform
    environment: Subscription-NonProdEnterprise
    dependsOn:
      - Init_NonProdEnterprise_TFState
    strategy:
      runOnce:
        deploy:
          steps:
          - template: template-terraform.yml
            parameters: 
              service_connection: '$(Azure.Subscription.NonProdEnterprise)'
              terraform_work_directory: '$(Build.SourcesDirectory)/terraform/subscription'
              tfstate_rg_name: $(Tf.State.NonProdEnterprise.RG)
              tfstate_storage_account_name: $(Tf.State.NonProdEnterprise.SA)
              tfstate_blob_name: $(Tf.State.NonProdEnterprise.Blob)
              tfstate_file_name: 'enterprise'
              spoke_vars_file_name: 'enterprise'
              additional_command_options: ''

- ${{ if eq(variables['deploy.nonprod'], 'true') }}:
  - stage: Provision_NonProd
    displayName: Provision NonProd Platform
    dependsOn:
      - Provision_NonProdEnterprise_Subscription
    jobs:
    - deployment: Provision_Platform_NonProd
      displayName: Provision NonProd Platform
      environment: NonProd
      strategy:
        runOnce:
          deploy:
            steps:
            - template: template-terraform.yml
              parameters: 
                service_connection: '$(Azure.Subscription.NonProdEnterprise)'
                terraform_work_directory: '$(Build.SourcesDirectory)/terraform/environment'
                tfstate_rg_name: $(Tf.State.NonProdEnterprise.RG)
                tfstate_storage_account_name: $(Tf.State.NonProdEnterprise.SA)
                tfstate_blob_name: $(Tf.State.NonProdEnterprise.Blob)
                tfstate_file_name: 'nonprod'
                spoke_vars_file_name: 'nonprod'
                additional_command_options: ''
            
  - ${{ if eq(variables['deploy.prod'], 'true') }}:
    - stage: Provision_ProdPremium_Subscription
      displayName: Provision Production Premium Subscription
      dependsOn:
        - Provision_NonProd
      jobs:
      - job: Init_ProdPremium_TFState
        displayName: Init ProdPremium TFState
        steps:
        - template: create-tfstate-storage.yml
          parameters:
            location: 'uksouth'
            service_connection: $(Azure.Subscription.ProdPremium)
            resource_group_name: $(Tf.State.ProdPremium.RG)
            storage_account_name: $(Tf.State.ProdPremium.SA)
            container_blob_name: $(Tf.State.ProdPremium.Blob)

      - deployment: Provision_ProdPremium_Platform
        displayName: Provision ProdPremium Platform
        environment: Subscription-ProdPremium
        dependsOn:
          - Init_ProdPremium_TFState
        strategy:
          runOnce:
            deploy:
              steps:
              - template: template-terraform.yml
                parameters: 
                  service_connection: '$(Azure.Subscription.ProdPremium)'
                  terraform_work_directory: '$(Build.SourcesDirectory)/terraform/subscription'
                  tfstate_rg_name: $(Tf.State.ProdPremium.RG)
                  tfstate_storage_account_name: $(Tf.State.ProdPremium.SA)
                  tfstate_blob_name: $(Tf.State.ProdPremium.Blob)
                  tfstate_file_name: 'enterprise'
                  spoke_vars_file_name: 'enterprise'
                  additional_command_options: ''